### ISSUE TITLE
--rip-lib

### ISSUE THREAD

**Issue by STEK1337** [luxysiv/revanced-nonroot#1]
Is it possible to switch to https://github.com/j-hc/revanced-cli so we can use --rip-lib?

**Comment by luxysiv** [comment]
What do you mean??? I don't know --rip-lib? What is is?

**Comment by STEK1337** [comment]
--rip-lib x86_64 --rip-lib x86, remove x64 & x86 libs, only arm7 and arm8 stays, cleans APKs from unneeded libs to make them smaller

**Comment by luxysiv** [comment]
I don't know exactly what you want but I can give you some suggestions. First, you can delete revanced-cli in dl_gh function, and you add  dl_gh_cli to download revanced-cli from j-hc. You can add --rip-lib x86_64 --rip-lib x86 command in patch function. Good luck. Tell me if it successfully. Thanks. Sorry about my English

**Comment by STEK1337** [comment]
It worked, thank you

**Comment by luxysiv** [comment]
@STEK1337 you fork repository from person, who download and up my code. Now she create thread but don't talk about it's my code

**Comment by STEK1337** [comment]
Deleted the fork. Thanks for the info

**Comment by luxysiv** [comment]
You know, I told she about ---rip lib when you open this issue because I think no need. And she copy my code about download apk mirror with arch. She ask Bing. First, she open a thread on forum in Vietnam.She said :" Sau bao thử nghiệm thì repository của mình đã hoạt động trơn tru nhất" > "After many tests, my repository has worked the most smoothly" .She don't talk about download and up code from my repository, I warning on telegram. I asked to say fork and link my repository.  When I click on the link it shows a blank page.  Then I asked to remove the line she mentioned above, she deleted the post.  I let it go, but now she wrote: "I was created".  I said on the forum that she is a moderator, not to write like that.  She said I'm like a mad dog that goes into fits from time to time.  WTF .  Now that text is still on her readme

**Comment by luxysiv** [comment]
About 2 months ago, I wrote the script as if it was not a test build, she took the code to run and it worked wrong.  She didn't text me that I did something wrong, but silently reverted to the previous code.

**Comment by luxysiv** [comment]
Do you think about [this](https://github.com/manhduonghn/revanced-extended)

**Comment by luxysiv** [comment]
I will be update my code to split 4 architectures

**Comment by luxysiv** [comment]
![Screenshot_2023-06-20-16-46-32-341_com lemurbrowser exts](https://github.com/luxysiv/revanced-nonroot/assets/46205571/cc4f85e1-3bdd-4300-ab43-f7d134795b44)
